// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[...all]': typeof import('./src/pages/[...all].vue')['default']
    AsidePanel: typeof import('./src/templates/AsidePanel.vue')['default']
    Auth: typeof import('./src/pages/auth/index.vue')['default']
    AuthLayout: typeof import('./src/templates/AuthLayout.vue')['default']
    AuthLogIn: typeof import('./src/organisms/Auth/AuthLogIn.vue')['default']
    AuthSignUp: typeof import('./src/organisms/Auth/AuthSignUp.vue')['default']
    CalendarBody: typeof import('./src/molecules/CalendarBody.vue')['default']
    CalendarHeader: typeof import('./src/molecules/CalendarHeader.vue')['default']
    CalendarStats: typeof import('./src/molecules/CalendarStats.vue')['default']
    ChartWrapper: typeof import('./src/organisms/ChartWrapper.vue')['default']
    CrossTable: typeof import('./src/templates/CrossTable.vue')['default']
    CrossTableTD: typeof import('./src/atoms/CrossTable/CrossTableTD.vue')['default']
    CrossTableTH: typeof import('./src/atoms/CrossTable/CrossTableTH.vue')['default']
    DatePicker: typeof import('./src/organisms/DatePicker.vue')['default']
    FilterMode: typeof import('./src/molecules/FilterMode.vue')['default']
    Panel: typeof import('./src/pages/panel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectPicker: typeof import('./src/organisms/SelectPicker.vue')['default']
    StatsPanel: typeof import('./src/organisms/StatsPanel.vue')['default']
    Undefined: typeof import('./src/pages/index.vue')['default']
    ValidateInput: typeof import('./src/molecules/ValidateInput.vue')['default']
    VLabelInput: typeof import('./src/atoms/V/VLabelInput.vue')['default']
    VTab: typeof import('./src/organisms/V/VTab.vue')['default']
  }

}
