// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[...all]': typeof import('./src/pages/[...all].vue')['default']
    AsidePanel: typeof import('./src/organisms/AsidePanel.vue')['default']
    Auth: typeof import('./src/pages/auth/index.vue')['default']
    AuthLayout: typeof import('./src/templates/AuthLayout.vue')['default']
    ChartWrapper: typeof import('./src/organisms/ChartWrapper.vue')['default']
    CrossTable: typeof import('./src/templates/CrossTable.vue')['default']
    CrossTableTD: typeof import('./src/atoms/CrossTable/CrossTableTD.vue')['default']
    CrossTableTH: typeof import('./src/atoms/CrossTable/CrossTableTH.vue')['default']
    CustomInput: typeof import('./src/molecules/CustomInput.vue')['default']
    DatePicker: typeof import('./src/organisms/DatePicker.vue')['default']
    LabelInput: typeof import('./src/atoms/LabelInput.vue')['default']
    LogIn: typeof import('./src/organisms/LogIn.vue')['default']
    Panel: typeof import('./src/pages/panel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectPicker: typeof import('./src/organisms/SelectPicker.vue')['default']
    SignUp: typeof import('./src/organisms/SignUp.vue')['default']
    StatsPanel: typeof import('./src/organisms/StatsPanel.vue')['default']
    Tab: typeof import('./src/templates/Tab.vue')['default']
    Undefined: typeof import('./src/pages/index.vue')['default']
  }

}
