// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    "[...all]": typeof import("./src/pages/[...all].vue")["default"];
    AsidePanel: typeof import("./src/templates/AsidePanel.vue")["default"];
    Auth: typeof import("./src/pages/auth/index.vue")["default"];
    AuthLayout: typeof import("./src/templates/AuthLayout.vue")["default"];
    AuthLogIn: typeof import("./src/organisms/Auth/AuthLogIn.vue")["default"];
    AuthSignUp: typeof import("./src/organisms/Auth/AuthSignUp.vue")["default"];
    CalendarBody: typeof import("./src/molecules/Calendar/CalendarBody.vue")["default"];
    CalendarFilterMode: typeof import("./src/molecules/Calendar/CalendarFilterMode.vue")["default"];
    CalendarHeader: typeof import("./src/molecules/Calendar/CalendarHeader.vue")["default"];
    CalendarStats: typeof import("./src/molecules/Calendar/CalendarStats.vue")["default"];
    CrossTable: typeof import("./src/templates/CrossTable.vue")["default"];
    CrossTableTD: typeof import("./src/atoms/CrossTable/CrossTableTD.vue")["default"];
    CrossTableTH: typeof import("./src/atoms/CrossTable/CrossTableTH.vue")["default"];
    DatePicker: typeof import("./src/organisms/DatePicker.vue")["default"];
    ErrorNotification: typeof import("./src/molecules/V/ErrorNotification.vue")["default"];
    Panel: typeof import("./src/pages/panel/index.vue")["default"];
    RadarChart: typeof import("./src/organisms/V/RadarChart.vue")["default"];
    RadarWrapper: typeof import("./src/organisms/RadarWrapper.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    StatsPanel: typeof import("./src/organisms/StatsPanel.vue")["default"];
    Undefined: typeof import("./src/pages/index.vue")["default"];
    ValidateInput: typeof import("./src/molecules/V/ValidateInput.vue")["default"];
    VLabelInput: typeof import("./src/atoms/V/VLabelInput.vue")["default"];
    VModal: typeof import("./src/templates/VModal.vue")["default"];
    VTab: typeof import("./src/organisms/V/VTab.vue")["default"];
  }
}
